# Pandas

### Creating Series Data Structure

In [ ]:
import pandas as pd
import numpy as np

#Create from ndarray
data = np.array(['a', 'b', 'c', 'd', 'e'])
s = pd.Series(data)
print('Series s created from ndarray \n', s)

Series s created from ndarray
 0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
#Create from ndarray with label
t = pd.Series(data, index=[100,101,102,103,104])
print('Series t created from ndarray with label \n', t)

Series t created from ndarray with label
 100    a
101    b
102    c
103    d
104    e
dtype: object

In [ ]:
#Create From dict 
data2 = {'a':0, 'b':1.5, 'c':2.5}
d = pd.Series(data2)
print('Sereies d created from dict \n', d)

Sereies d created from dict
 a    0.0
b    1.5
c    2.5
dtype: float64

## Accessing Elements from a Series Data Structure

In [ ]:
#This is to create the Series for explaining accessing the data
s= pd.Series(np.arange(1,9), index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
print(s)

#Access by the integer index
print('Element at position 1 is : ', s[1])

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64
Element at position 1 is :  2

In [ ]:
#Access a range of elements
print('Elements from postion 1 to 5: \n ', s[1:5])

Elements from postion 1 to 5:
  b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#Access the first 5 elements
print('First 5 elements \n', s[:5])

First 5 elements
 a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#Accest the last 3 elements
print('Last 3 elements \n', s[-3:])

Last 3 elements
 f    6
g    7
h    8
dtype: int64

In [ ]:
#Access the element by label(index)
print('Eements by Label \n', s['c'])

print('Eements by Label \n', s[['a', 'c']])

Eements by Label
 3
Eements by Label
 a    1
c    3
dtype: int64

### Data Frame Data Structure

DataFrame are:
* Two Dimensional labelled respectively
* Data can be heterogeneous
* Size and data is mutable
* Able to perform Arithmetic operations on rows and columns

![image.png]()

Data Frame can be created from the following inputs
* Lists
* Dict
* Series
* Ndarray
* Another Data Frame

In [ ]:
#Create from a list of data
listData = [1, 3,5,6,8, 10]
listDF = pd.DataFrame(listData)
print('Created from List\n')
print(listDF)

Created from List

    0
0   1
1   3
2   5
3   6
4   8
5  10

In [ ]:
print('Created from List')
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

Created from List
     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

In [ ]:
print('Created from List')
print('Define the data type for age \n')
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

Created from List
Define the data type for age

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0

In [ ]:
print('Created from ndarray')
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'], 'Age':[28,34,29,42]}
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

Created from ndarray
    Name   Age
0    Tom  28.0
1   Jack  34.0
2  Steve  29.0
3  Ricky  42.0

In [ ]:
print('Created from List')
print('This example is created as an indexed(labelled DataFrame \n')
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print(df)

Created from List
This example is created as an indexed(labelled DataFrame

        Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42

In [ ]:
print('Created from List of Dict')
data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
print(df)

Created from List of Dict
   a   b     c
0  1   2   NaN
1  5  10  20.0

## Loading data from csv files

csv file can be loaded into the DataFrame using **pandas.read_csv()**

Mount our google drive before we can access any files stored on our google drive.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = "/content/drive/My Drive/Colab Notebooks/IPRAD/Iris.csv"
#Reading from Students.csv
df = pd.read_csv(file_path)
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Row Selection and Slicing

The row from the Dataframe can be retrieved by label or integer
* Use loc  to retrieve by label
* Use iloc to retrieve by integer

In [ ]:
d = {'one' : pd.Series([1, 4, 3,4], index=['a', 'b', 'c','e']),
    'two' : pd.Series([1, 5, 3, 4, 8], index=['a', 'b', 'c', 'd','e']),
    'three' : pd.Series([5, 15, 13, 4,9], index=['a', 'b', 'c', 'd','f'])}
df = pd.DataFrame(d)
# Original Data Frame
print('Original Data Frame')
df.head()

Original Data Frame

   one  two  three
a  1.0  1.0    5.0
b  4.0  5.0   15.0
c  3.0  3.0   13.0
d  NaN  4.0    4.0
e  4.0  8.0    NaN

In [ ]:
# Selection of Row by Labels
print('Selection of Row b')
print (df.loc['b'])

Selection of Row b
one       4.0
two       5.0
three    15.0
Name: b, dtype: float64

In [ ]:
#Selection of Row by range of label
print('Selection of Range of Row ')
print (df.loc['b':'d'])

Selection of Range of Row
   one  two  three
b  4.0  5.0   15.0
c  3.0  3.0   13.0
d  NaN  4.0    4.0

In [ ]:
# Selection of Row by Integer
print('Selection of Row 3 ')
print (df.iloc[3])

Selection of Row 3
one      NaN
two      4.0
three    4.0
Name: d, dtype: float64

In [ ]:
# Selection of Row by range of Integer
print('Selection of Range of Row')
print (df.iloc[3:5])

Selection of Range of Row
   one  two  three
d  NaN  4.0    4.0
e  4.0  8.0    NaN

## Display Specific Data Frame columns

In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'], 'Age':[28,34,29,42],'Marks':[55.5, 79.5, 30.5, 80]}
df = pd.DataFrame(data,columns=['Name','Age', 'Marks'],dtype=float)
df

    Name   Age  Marks
0    Tom  28.0   55.5
1   Jack  34.0   79.5
2  Steve  29.0   30.5
3  Ricky  42.0   80.0

In [ ]:
# Retrieving Specific Columns
df_Col = df[['Name', 'Marks']]
df_Col

    Name  Marks
0    Tom   55.5
1   Jack   79.5
2  Steve   30.5
3  Ricky   80.0

## Adding a new column to existing DataFrame

In [ ]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
    'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print ("Original Data Frame \n")
df

Original Data Frame

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [ ]:
#A new column is added to the dataframe from a series
print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
df

Adding a new column by passing as Series:

   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN

The advantage of using the index (label) is to indicate the row of where the elements should be added. The index here is an optional parameter

In [ ]:
#Add a new column from existing columns
print ("Adding a new column using the existing columns in DataFrame:")
df['four']=df['one']+df['three']
df

Adding a new column using the existing columns in DataFrame:

   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN

## Slicing the DataFrame

In [ ]:
d = {'one' : pd.Series([1, 4, 3,4], index=['a', 'b', 'c','e']),
    'two' : pd.Series([1, 5, 3, 4, 8], index=['a', 'b', 'c', 'd','e']),
    'three' : pd.Series([5, 15, 13, 4,9], index=['a', 'b', 'c', 'd','f'])}
df = pd.DataFrame(d)

# Slicing the Dataframe
print('Slicing the DataFrame')
df[3:5]

Slicing the DataFrame

   one  two  three
d  NaN  4.0    4.0
e  4.0  8.0    NaN

## Delete column from Data Frame

In [ ]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd']),
     'three' : pd.Series([10,20,30], index=['a','b','c'])}
df = pd.DataFrame(d)
print('Original Data Frame \n')
df

Original Data Frame

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [ ]:
#Using the Del Function
print('Delete a column using the del function')
del df['one']
df

Delete a column using the del function

   two  three
a    1   10.0
b    2   20.0
c    3   30.0
d    4    NaN

In [ ]:
#Using Pop function
print('Delete column using the pop function')
df.pop('two')
df

Delete column using the pop function

   three
a   10.0
b   20.0
c   30.0
d    NaN

## Sorting

There maybe incidents where there is a need to sort the data 
E.g. Analyzing and training certain range of data.
There are two sorting available in Pandas:
* By Label
* By Actual Value 

The array can by sorted by the **label**(index) using **sort_index**()

In [ ]:
# Create the unsorted data
unsorted_data=pd.DataFrame({'Col1':[5, 10,3, 8, 9 ], 'Col2':[3,4,2,5, 9], 'Col3': [4,0,5, 3,2] }, index=[4, 2, 5,1,6] )
print('Unsorted Data')
unsorted_data

Unsorted Data

   Col1  Col2  Col3
4     5     3     4
2    10     4     0
5     3     2     5
1     8     5     3
6     9     9     2

In [ ]:
# Sort the data by Label
sort_byLabel = unsorted_data.sort_index()
print('Sorting by label (index)')
sort_byLabel

Sorting by label (index)

   Col1  Col2  Col3
1     8     5     3
2    10     4     0
4     5     3     4
5     3     2     5
6     9     9     2

In [ ]:
# Order of Sorting by Label
sort_byLabel2 = unsorted_data.sort_index(ascending=False)
print('Sorting by label (index) in descending order')
sort_byLabel2

Sorting by label (index) in descending order

   Col1  Col2  Col3
6     9     9     2
5     3     2     5
4     5     3     4
2    10     4     0
1     8     5     3

**Sorting by Values**

The array can by sorted by the **label**(index) using **sort_value**(). It accept a **‘by’** argument to determine which column to sort

The array can be sorted by multiple column. For example, sort_value(by=[‘col1’, ‘col2’]), the array will be sorted by col1 followed by col2

In [ ]:
unsorted_df= pd.DataFrame({'col1':[2,4,1,3],'col2':[1,6,3,7],
                           'col3':[6,1,3,2], 'col4':[3,5,2,4]})
# Original Unsorted Array
print('Original Unsorted Array')
unsorted_df

Original Unsorted Array

   col1  col2  col3  col4
0     2     1     6     3
1     4     6     1     5
2     1     3     3     2
3     3     7     2     4

In [ ]:
# Sorting by Col1
print('Sort the array by Col1')
sorted_df=unsorted_df.sort_values(by='col1')
sorted_df

Sort the array by Col1

   col1  col2  col3  col4
2     1     3     3     2
0     2     1     6     3
3     3     7     2     4
1     4     6     1     5

In [ ]:
# Sorting by Col1 and cCol2
print('Sort the array by Col1 then by Col2')
sorted_df=unsorted_df.sort_values(by=['col1','col2'])
sorted_df

Sort the array by Col1 then by Col2

   col1  col2  col3  col4
2     1     3     3     2
0     2     1     6     3
3     3     7     2     4
1     4     6     1     5

**Sorting using Algorithm**

**sort_values**() has a provision to choose the algorithm from mergesort, heapsort and quicksort

In [ ]:
# Using Megasort
sorted_df=unsorted_df.sort_values(by='col1' ,kind='mergesort')
print('Using Megasort')
sorted_df

Using Megasort

   col1  col2  col3  col4
2     1     3     3     2
0     2     1     6     3
3     3     7     2     4
1     4     6     1     5

## Exercise

***Exercise  1*** :  Load a file using Pandas read_csv functions
1.	Copy the given file ‘health.csv’ into ‘/home/cet/Data’ folder if necessary
2.	Create the DataFrame health_df by reading the file ‘health.csv’ using read_csv()
3.	Display the DataFrame

***Exercise 2***: Sort by values
1.	Use the DataFrame created in the previous exercise,
2.	Sort ‘health_df’ by ‘Weight’ (By Values) and call the new DataFrame called ‘sorted_byWeight’ 
3.	Display the new DataFrame

***Exercise 3***: Add a New Columns
1.	Use the Dataset created from previous exercise
2.	You are required to add a new column called ‘Weight_in_kg’
3.	Formula for the new weight is ‘Weight/2.2’

## Merging Data Frame

Pandas has merge features that allow to join two DataFrames using the ‘merge’ function

In [ ]:
# Reading Data from the studentInfo and studentGrade files
file_path = "/content/drive/My Drive/Colab Notebooks/IPRAD/studentInfo.csv"
student_df = pd.read_csv(file_path)
file_path = "/content/drive/My Drive/Colab Notebooks/IPRAD/studentGrade.csv"
studgrade_df = pd.read_csv(file_path)

In [ ]:
# Merge the DataFrame based on the StudentID
studperf_df= pd.merge(student_df, studgrade_df, on='studentID' )
studperf_df

   studentID       StudentName Gender  ...  Chemistry  Mathematics  Mother_Tongue
0       S001       Tan Ah Beng      M  ...         88           80             70
1       S002     Teo Geok Huey      F  ...         45           33             74
2       S003         Mary Tan       F  ...         95           79             88
3       S004   Richard F. John      M  ...         60           57             64
4       S005          Andy Lee      M  ...         59           69             40
5       S006      Mohd Firadus      M  ...         93           94             96
6       S007         Sarah Lee      F  ...         44           50             40
7       S008          Lulu Tan      F  ...         30           40             40
8       S009     Carol Husband      F  ...         80           95             88
9       S010       Michael Low      M  ...         70           60             65
10      S011      Lee Wai Ming      M  ...         81           91             91
11      S012       Lee Eng Tok      M  ...         56           64             64
12      S013     Geraldine Loh      F  ...         96           94             92
13      S014  Marget D/O Surah      F  ...         60           88             92
14      S015     Clark Johnson      M  ...         50           45             30
15      S016          Dick Tan      M  ...         55           55             35

[16 rows x 7 columns]

## Descriptive Statistic

Pandas like NumPy has statistical functions

![image.png]()

In [ ]:
#Create a Dictionary of series
d={'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
                     'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])
}
#Create a DataFrame
df = pd.DataFrame(d)
print('Original Data')
df

Original Data

      Name  Age  Rating
0      Tom   25    4.23
1    James   26    3.24
2    Ricky   25    3.98
3      Vin   23    2.56
4    Steve   30    3.20
5    Smith   29    4.60
6     Jack   23    3.80
7      Lee   34    3.78
8    David   40    2.98
9   Gasper   30    4.80
10  Betina   51    4.10
11  Andres   46    3.65

In [ ]:
# Computing the mean of the Age and Rating
print('Compute the mean of the Age and Rating')
df.mean()

Compute the mean of the Age and Rating

Age       31.833333
Rating     3.743333
dtype: float64

In [ ]:
# Compute the Standard Deviation
print('Compute the Standard Deviation of Age and Rating')
df.std()

Compute the Standard Deviation of Age and Rating

Age       9.232682
Rating    0.661628
dtype: float64

In [ ]:
# Compute the Max and min Age and Rating
print('Determine the Max and Min of the Age and Rating')
print('Max Age and Rating')
df.max()

Determine the Max and Min of the Age and Rating
Max Age and Rating

Name      Vin
Age        51
Rating    4.8
dtype: object

In [ ]:
print('Min Age and Rating')
df.min()

Min Age and Rating

Name      Andres
Age           23
Rating      2.56
dtype: object

## Exercise 
1.	Using the files 'studentInfo.csv'  and 'studentGrade.csv', write the code to read the two files into TWO DataFrames
3.	Merge the TWO dataFrame by using the studentID and called the new DataFrame studentPerf_DF
4.	List ALL female students that have failed the Mother_tongue.
5.	Display only the ‘StudentID’, ‘StudentName’ and the ‘Mother_Tongue’ Columns

In [ ]:
import numpy as np
import pandas as pd

df_stdInfo=pd.read_csv(_BLANK_)
df_stdGrade=pd.read_csv(_BLANK_)
df_stdPerf = pd.merge(df_stdInfo,df_stdGrade, on=_BLANK_ )
df_stdPerf